// src/utils/import-tiles.ts
import nan from '../tiles/nan.svg';
import chun from '../tiles/chun.svg';
import haku from '../tiles/haku.svg';
import hatsu from '../tiles/hatsu.svg';
import man1 from '../tiles/man1.svg';
import man2 from '../tiles/man2.svg';
import man3 from '../tiles/man3.svg';
import man4 from '../tiles/man4.svg';
import man5 from '../tiles/man5.svg';
import man6 from '../tiles/man6.svg';
import man7 from '../tiles/man7.svg';
import man8 from '../tiles/man8.svg';
import man9 from '../tiles/man9.svg';
import pin1 from '../tiles/pin1.svg';
import pei from '../tiles/pei.svg';
import man5d from '../tiles/man5d.svg';
import pin2 from '../tiles/pin2.svg';
import pin3 from '../tiles/pin3.svg';
import pin4 from '../tiles/pin4.svg';
import pin5 from '../tiles/pin5.svg';
import pin6 from '../tiles/pin6.svg';
import pin7 from '../tiles/pin7.svg';
import pin8 from '../tiles/pin8.svg';
import pin9 from '../tiles/pin9.svg';
import sou1 from '../tiles/sou1.svg';
import pin5d from '../tiles/pin5d.svg';
import shaa from '../tiles/shaa.svg';
import sou2 from '../tiles/sou2.svg';
import sou3 from '../tiles/sou3.svg';
import sou4 from '../tiles/sou4.svg';
import sou5 from '../tiles/sou5.svg';
import sou6 from '../tiles/sou6.svg';
import sou7 from '../tiles/sou7.svg';
import sou8 from '../tiles/sou8.svg';
import sou9 from '../tiles/sou9.svg';
import sou5d from '../tiles/sou5d.svg';
import ton from '../tiles/ton.svg';

const images = [nan, chun, haku, hatsu, man1, man2, man3, man4, man5, man6, man7, man8, man9, pin1, pei, man5d, pin2, pin3, pin4, pin5, pin6, pin7, pin8, pin9, sou1, pin5d, shaa, sou2, sou3, sou4, sou5, sou6, sou7, sou8, sou9, sou5d, ton];

export default images;
